name: test

on: workflow_dispatch

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Run Stuff
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v0.16.0/oras_0.16.0_linux_amd64.tar.gz
          mkdir -p oras-install/
          tar -zxf oras_0.16.0_*.tar.gz -C oras-install/
          mv oras-install/oras /usr/local/bin/
          rm -rf oras_0.16.0_*.tar.gz oras-install/
          oras version
          echo ${{ github.token }} | oras login ghcr.io -u ${{ github.actor }} --password-stdin
          REPOSITORY=$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')
          oras push ghcr.io/$REPOSITORY/${{ github.event.repository.name }}:latest  ./src/:application/vnd.stackspot.stack+tar

#        oras pull ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}:latest
